apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-vol1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: app-cispark-v1
    path: "/exports/kafka"
