apiVersion: v1
kind: BuildConfig
metadata:
  name: kafkanetes
  namespace: explore-example
  selfLink: /oapi/v1/namespaces/explore-example/buildconfigs/kafkanetes
  uid: 723df593-0a60-11e7-b4e0-005056112152
  resourceVersion: '1860358'
  creationTimestamp: '2017-03-16T15:51:40Z'
  labels:
    app: kafkanetes-build
spec:
  triggers:
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/obpeter/oc-kafka.git'
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'kafkanetes:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
  lastVersion: 8
