apiVersion: v1
kind: DeploymentConfig
metadata:
  name: kafkanetes-zk-1
  namespace: explore-example
  selfLink: /oapi/v1/namespaces/explore-example/deploymentconfigs/kafkanetes-zk-1
  uid: f36f2f2c-0d3a-11e7-b4e0-005056112152
  resourceVersion: '1844723'
  generation: 23
  creationTimestamp: '2017-03-20T07:00:50Z'
  labels:
    app: kafkanetes-deploy-zk-3
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        containerNames:
          - kafkanetes
        from:
          kind: ImageStreamTag
          namespace: explore-example
          name: '172.30.10.104:5000/explore-example/kafkanetes'
  replicas: 1
  test: false
  selector:
    deploymentconfig: kafkanetes-zk-1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafkanetes-zk
        deploymentconfig: kafkanetes-zk-1
    spec:
      volumes:
        - name: zookeeper
          persistentVolumeClaim:
            claimName: kafkanetes-zk-1
      containers:
        - name: kafkanetes
          image: '172.30.10.104:5000/explore-example/kafkanetes'
          command:
            - bin/zookeeper-server-start-multiple.sh
          args:
            - config/zookeeper.properties
            - kafkanetes-zk
            - '1'
            - '3'
          ports:
            - containerPort: 2181
              protocol: TCP
            - containerPort: 2888
              protocol: TCP
            - containerPort: 3888
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: zookeeper
              mountPath: /tmp/zookeeper
              subPath: zk-1
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        supplementalGroups:
          - 5555
          - 50035
status:
  latestVersion: 10
  observedGeneration: 23
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastTransitionTime: '2017-03-28T14:26:12Z'
      reason: NewReplicationControllerAvailable
      message: Replication controller "kafkanetes-zk-1-10" has completed progressing
    - type: Available
      status: 'True'
      lastTransitionTime: '2017-04-03T11:04:21Z'
      message: Deployment config has minimum availability.
