apiVersion: v1
kind: Service
metadata:
  name: kafkanetes-kafka-1
  namespace: explore-example
  selfLink: /api/v1/namespaces/explore-example/services/kafkanetes-kafka-1
  uid: eb5f337b-1077-11e7-92c7-005056112152
  resourceVersion: '1429306'
  creationTimestamp: '2017-03-24T09:54:49Z'
  labels:
    app: kafkanetes-deploy-kafka-service-1
spec:
  ports:
    - name: 9093-secure
      protocol: TCP
      port: 9093
      targetPort: 9093
    - name: 9092-tcp
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    deploymentconfig: kafkanetes-kafka-1
  clusterIP: 172.30.133.181
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
