apiVersion: v1
kind: DeploymentConfig
metadata:
  name: registry-console
  namespace: default
  selfLink: /oapi/v1/namespaces/default/deploymentconfigs/registry-console
  uid: cb5d0968-fe9c-11e6-9734-005056112152
  resourceVersion: '1844981'
  generation: 2
  creationTimestamp: '2017-03-01T16:33:26Z'
  labels:
    app: registry-console
    createdBy: registry-console-template
    name: registry-console
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  triggers:
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    name: registry-console
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: registry-console
        name: registry-console
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: registry-console
          image: 'registry.access.redhat.com/openshift3/registry-console:3.3'
          ports:
            - containerPort: 9090
              protocol: TCP
          env:
            - name: OPENSHIFT_OAUTH_PROVIDER_URL
              value: 'https://app-cimaster-v1.fhm.de:8443'
            - name: OPENSHIFT_OAUTH_CLIENT_ID
              value: cockpit-oauth-client
            - name: KUBERNETES_INSECURE
              value: 'false'
            - name: COCKPIT_KUBE_INSECURE
              value: 'false'
            - name: REGISTRY_ONLY
              value: 'true'
            - name: REGISTRY_HOST
              value: docker-registry-default.fhm.de
          resources: {}
          livenessProbe:
            httpGet:
              path: /ping
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 9090
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 1
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  details:
    message: config change
    causes:
      - type: ConfigChange
  conditions:
    - type: Progressing
      status: 'True'
      lastTransitionTime: '2017-03-01T16:34:11Z'
      reason: NewReplicationControllerAvailable
      message: Replication controller "registry-console-1" has completed progressing
    - type: Available
      status: 'True'
      lastTransitionTime: '2017-04-03T11:08:02Z'
      message: Deployment config has minimum availability.
